language: python
python:
- '3.4'
- '3.5'
install: pip install -r requirements.txt
script: nosetests
deploy:
  provider: heroku
  api_key:
    secure: h3qsdoWa1TkAaP93IrzfruMa8U5/DJRjlnFbkGSx/FqQUey06IwL6CRJgWZ4e42+q1NPFpEnXdzpWAzlXVNeT1plAI0rPeTjIAXzcStTZ6FsHLPcWGqOVGm1XVtPGWGCtBrechibV+o30x2/6oCtBift+b9zmmtY85kVBr6VSD+S7gYoFU5PnrbdxQXa+qJXUojwWPPo8zkQvxdockzhNpQ44jSYTd/E27smWpw4MLIxfjzwtLcgJyT9e+W46kecm1VViJvjjZaBBAhY3JvFOTyAyXy3CMqePg7Nzbrt92r/zbqwwJouCZ2h4H1eIolQCiutLOmzE1M615rgLieaStLKbShZtZCMl5bx95RqgTx8r5A7ia8U5MMz7qNH1pcXI++9/FnotlXNNrlNxBJHx/6y9sL1fdhlJSHrALG8tze6zswjFfQcBnohTL2GVgILgWQC2ANfAe2XJGBZCz7dJhRsFUU2x/VK23TgQr1UDK2xu8hVgQ6GMk0GfODvYQLuEkbB9E4rdd6BDC+Z17v5zdvW+6tFvn6woH1KelkwmQ4ZhIv6Bz9TQj/DnG4MWCzw5qiIVILyUiUvOddQC2w7uQ7HH1QqVe4TQP2gaBY+mYeF/DmhT7lJ91S/HnzudPHIZEHJDPzpQz65ErN41J05HCjAHtMEl96s2e8/E/hcwSo=
